import { pool } from "../config/database";

export const LEAD_STATUS_VALUES = [
  "new",
  "contacted",
  "in_progress",
  "completed",
  "archived",
] as const;

export type LeadStatus = (typeof LEAD_STATUS_VALUES)[number];

export const LEAD_TYPE_VALUES = [
  "contact",
  "consultation",
  "health_checkup",
  "lead_magnet",
] as const;

export type LeadType = (typeof LEAD_TYPE_VALUES)[number];

export type NormalizedLead = {
  id: string;
  type: LeadType;
  name: string;
  company: string | null;
  email: string;
  phone: string;
  source: string;
  status: LeadStatus;
  createdAt: string;
  updatedAt: string;
};

export type LeadListParams = {
  page: number;
  limit: number;
  search?: string;
  status?: LeadStatus;
  type?: LeadType;
};

export type LeadListResult = {
  data: NormalizedLead[];
  pagination: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
  };
};

/**
 * A single UNION ALL view across every lead-generation table, normalized to
 * one shape. `type` and `source` are fixed string literals owned by this
 * file — never user input — so building this SQL string is not an
 * injection surface. Every *value* the caller supplies (search, status,
 * type, limit, offset) is still passed as a parameterized argument below,
 * never concatenated into the query text.
 */
const NORMALIZED_LEADS_CTE = `
  SELECT id, 'contact'::text AS type, name, company, email, phone,
         'Contact Form'::text AS source, status, created_at, updated_at
    FROM contact_leads
  UNION ALL
  SELECT id, 'consultation'::text AS type, name, company, email, phone,
         'Consultation Request'::text AS source, status, created_at, updated_at
    FROM consultation_requests
  UNION ALL
  SELECT id, 'health_checkup'::text AS type, name, company, email, phone,
         'Business Health Checkup'::text AS source, status, created_at, updated_at
    FROM health_checkups
  UNION ALL
  SELECT id, 'lead_magnet'::text AS type, name, company, email, phone,
         resource AS source, status, created_at, updated_at
    FROM lead_magnet_leads
`;

function mapRowToLead(row: {
  id: string;
  type: string;
  name: string;
  company: string | null;
  email: string;
  phone: string;
  source: string;
  status: string;
  created_at: string;
  updated_at: string;
}): NormalizedLead {
  return {
    id: row.id,
    type: row.type as LeadType,
    name: row.name,
    company: row.company,
    email: row.email,
    phone: row.phone,
    source: row.source,
    status: row.status as LeadStatus,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

export async function listNormalizedLeads(
  params: LeadListParams,
): Promise<LeadListResult> {
  const conditions: string[] = [];
  const values: unknown[] = [];

  if (params.search && params.search.trim().length > 0) {
    values.push(`%${params.search.trim()}%`);
    const idx = values.length;
    conditions.push(
      `(t.name ILIKE $${idx} OR t.email ILIKE $${idx} OR COALESCE(t.company, '') ILIKE $${idx})`,
    );
  }

  if (params.status) {
    values.push(params.status);
    conditions.push(`t.status = $${values.length}`);
  }

  if (params.type) {
    values.push(params.type);
    conditions.push(`t.type = $${values.length}`);
  }

  const whereClause = conditions.length > 0 ? `WHERE ${conditions.join(" AND ")}` : "";

  const countResult = await pool.query<{ count: string }>(
    `SELECT COUNT(*)::text AS count FROM (${NORMALIZED_LEADS_CTE}) t ${whereClause}`,
    values,
  );
  const total = Number(countResult.rows[0]?.count ?? "0");

  const limit = params.limit;
  const offset = (params.page - 1) * params.limit;
  const limitIdx = values.length + 1;
  const offsetIdx = values.length + 2;

  const dataResult = await pool.query(
    `SELECT * FROM (${NORMALIZED_LEADS_CTE}) t
     ${whereClause}
     ORDER BY t.created_at DESC
     LIMIT $${limitIdx} OFFSET $${offsetIdx}`,
    [...values, limit, offset],
  );

  return {
    data: dataResult.rows.map(mapRowToLead),
    pagination: {
      page: params.page,
      limit: params.limit,
      total,
      totalPages: Math.max(1, Math.ceil(total / params.limit)),
    },
  };
}

/**
 * Full detail for a single lead. IDs are UUIDs generated by
 * gen_random_uuid() per-table, so a collision across tables is not a
 * realistic concern; this checks each lead-generation table in turn and
 * returns the first (and only) match with its full, type-specific fields.
 */
export async function getLeadDetailById(
  id: string,
): Promise<Record<string, unknown> | null> {
  const contact = await pool.query(
    `SELECT id, 'contact'::text AS type, name, company, email, phone,
            project_type, budget, timeline, message, status, created_at, updated_at
       FROM contact_leads WHERE id = $1`,
    [id],
  );
  if (contact.rows[0]) return contact.rows[0];

  const consultation = await pool.query(
    `SELECT id, 'consultation'::text AS type, name, company, email, phone,
            project_type, preferred_timeslot, message, status, created_at, updated_at
       FROM consultation_requests WHERE id = $1`,
    [id],
  );
  if (consultation.rows[0]) return consultation.rows[0];

  const healthCheckup = await pool.query(
    `SELECT id, 'health_checkup'::text AS type, name, company, email, phone,
            business_stage, digital_presence, technology_readiness,
            growth_priorities, goals, timeline, additional_information,
            status, created_at, updated_at
       FROM health_checkups WHERE id = $1`,
    [id],
  );
  if (healthCheckup.rows[0]) return healthCheckup.rows[0];

  const leadMagnet = await pool.query(
    `SELECT id, 'lead_magnet'::text AS type, name, company, email, phone,
            resource, status, created_at, updated_at
       FROM lead_magnet_leads WHERE id = $1`,
    [id],
  );
  if (leadMagnet.rows[0]) return leadMagnet.rows[0];

  return null;
}

/**
 * Which table a lead id belongs to, needed by the status-update route
 * before it can issue the right UPDATE. Returns null if not found in any
 * lead-generation table.
 */
const LEAD_TABLE_BY_TYPE: Record<LeadType, string> = {
  contact: "contact_leads",
  consultation: "consultation_requests",
  health_checkup: "health_checkups",
  lead_magnet: "lead_magnet_leads",
};

export async function findLeadType(id: string): Promise<LeadType | null> {
  for (const type of LEAD_TYPE_VALUES) {
    const table = LEAD_TABLE_BY_TYPE[type];
    // `table` is one of the four fixed literals above — never user input —
    // so interpolating it into the query text is not an injection surface.
    // The id value itself is always parameterized.
    // eslint-disable-next-line no-await-in-loop
    const result = await pool.query(`SELECT 1 FROM ${table} WHERE id = $1`, [id]);
    if (result.rows[0]) return type;
  }
  return null;
}

export async function updateLeadStatusById(
  id: string,
  type: LeadType,
  status: LeadStatus,
): Promise<Record<string, unknown> | null> {
  const table = LEAD_TABLE_BY_TYPE[type];
  const result = await pool.query(
    `UPDATE ${table} SET status = $1, updated_at = NOW() WHERE id = $2 RETURNING *`,
    [status, id],
  );
  if (!result.rows[0]) return null;
  return { ...result.rows[0], type };
}

// ---------------------------------------------------------------------------
// Dashboard statistics
// ---------------------------------------------------------------------------

export type DashboardStats = {
  totalLeads: number;
  contactLeads: number;
  consultations: number;
  healthCheckups: number;
  leadMagnets: number;
  applications: number;
  newLeads: number;
  contacted: number;
  inProgress: number;
  completed: number;
  archived: number;
};

export async function getDashboardStats(): Promise<DashboardStats> {
  const [
    contactCount,
    consultationCount,
    healthCheckupCount,
    leadMagnetCount,
    applicationCount,
    statusCounts,
  ] = await Promise.all([
    pool.query<{ count: string }>("SELECT COUNT(*)::text AS count FROM contact_leads"),
    pool.query<{ count: string }>(
      "SELECT COUNT(*)::text AS count FROM consultation_requests",
    ),
    pool.query<{ count: string }>("SELECT COUNT(*)::text AS count FROM health_checkups"),
    pool.query<{ count: string }>(
      "SELECT COUNT(*)::text AS count FROM lead_magnet_leads",
    ),
    pool.query<{ count: string }>("SELECT COUNT(*)::text AS count FROM applications"),
    // Status breakdown spans every lead-generation table AND applications,
    // since both surface a status the admin needs an at-a-glance count of.
    pool.query<{ status: string; count: string }>(
      `SELECT status, COUNT(*)::text AS count FROM (
         SELECT status FROM contact_leads
         UNION ALL SELECT status FROM consultation_requests
         UNION ALL SELECT status FROM health_checkups
         UNION ALL SELECT status FROM lead_magnet_leads
         UNION ALL SELECT status FROM applications
       ) t
       GROUP BY status`,
    ),
  ]);

  const contactLeads = Number(contactCount.rows[0]?.count ?? "0");
  const consultations = Number(consultationCount.rows[0]?.count ?? "0");
  const healthCheckups = Number(healthCheckupCount.rows[0]?.count ?? "0");
  const leadMagnets = Number(leadMagnetCount.rows[0]?.count ?? "0");
  const applications = Number(applicationCount.rows[0]?.count ?? "0");

  const byStatus: Record<string, number> = {};
  for (const row of statusCounts.rows) {
    byStatus[row.status] = Number(row.count);
  }

  return {
    totalLeads: contactLeads + consultations + healthCheckups + leadMagnets,
    contactLeads,
    consultations,
    healthCheckups,
    leadMagnets,
    applications,
    newLeads: byStatus["new"] ?? 0,
    contacted: byStatus["contacted"] ?? 0,
    inProgress: byStatus["in_progress"] ?? 0,
    completed: byStatus["completed"] ?? 0,
    archived: byStatus["archived"] ?? 0,
  };
}
